version: 2.1
parameters:
    COMPOSER_CACHE_VERSION:
      type: string
      default: v2
      description: 'Prefix of the cache keys. Change it if you want the next run to be cacheless.'
    NODE_CACHE_VERSION:
      type: string
      default: v2
      description: 'Prefix of the cache keys. Change it if you want the next run to be cacheless.'
orbs:
  slack: circleci/slack@4.1
  aws-s3: circleci/aws-s3@3.0
  node: circleci/node@4.7.0
jobs:
  test:
    docker:
      - image: circleci/php:7.2-stretch
      - image: circleci/mysql:8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: $MYSQL_USER
          MYSQL_DATABASE: $MYSQL_DATABASE
          MYSQL_PASSWORD: $MYSQL_PASSWORD
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql
      - node/install:
          install-yarn: true
      - run: node --version

      # composer cache
      - restore_cache:
          keys:
          # "composer.json" can be used if "composer.json"
          # is not committed to the repository.
          - composer-<< pipeline.parameters.COMPOSER_CACHE_VERSION >>-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - composer-<< pipeline.parameters.COMPOSER_CACHE_VERSION >>-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-<< pipeline.parameters.COMPOSER_CACHE_VERSION >>-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # node cache
      - restore_cache:
          keys:
            - node-<< pipeline.parameters.NODE_CACHE_VERSION >>-{{ checksum "package.json" }}
            - node-<< pipeline.parameters.NODE_CACHE_VERSION >>-
      - run: npm install
      - save_cache:
          key: node-<< pipeline.parameters.NODE_CACHE_VERSION >>-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      # prepare the database
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=mysql --force

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      # this example uses codecept but you're not limited to it
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run --xml result.xml
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
  build:
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://jasur-webinar-demo-bucket/laravel-demo/<<pipeline.number>>/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://jasur-webinar-demo-bucket/laravel-demo/<<pipeline.number>>/'
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  test-build-and-notify:
    jobs:
    - test
    - build:
        context: aws_secrets
    - notify:
        context: slack_secrets
        requires:
          - build
